" disable vi compatibility
set nocompatible

" plugins
if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent execute '!curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'sainnhe/everforest'
call plug#end()

" theme
syntax on
set termguicolors
set background=dark
colorscheme everforest

" line numbers
set number
set relativenumber

set nowrap

" cursor
let &t_SI.="\e[5 q" "SI = INSERT mode
let &t_SR.="\e[4 q" "SR = REPLACE mode
let &t_EI.="\e[1 q" "EI = NORMAL mode (ELSE)

" invisible characters
set list
set listchars=tab:→\ ,lead:·,trail:·,nbsp:+,eol:¬

" indent
set expandtab
set tabstop=2
set shiftwidth=2

" search
set incsearch
set hlsearch
set ignorecase

" no swap file
set noswapfile

" mappings
let mapleader = " "
nnoremap <leader>s :w<cr>
nnoremap <S-u> <C-r>
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap <C-f> <C-f>zz
nnoremap <C-b> <C-b>zz
inoremap jk <esc>
