" disable vi compatibility
set nocompatible

" plugins
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
Plug 'sainnhe/everforest'
call plug#end()

" line numbers
set number
set relativenumber

set nowrap

" search
set incsearch
set hlsearch
set ignorecase

" invisible characters
set list
set listchars=tab:→\ ,lead:·,trail:·,nbsp:+,eol:¬

" indent
set expandtab
set tabstop=2
set shiftwidth=2

" mappings
let mapleader = " "
nnoremap <leader>s :w<cr>
nnoremap <S-u> <C-r>
inoremap jk <esc>

syntax on
colorscheme everforest
