" disable vi compatibility
set nocompatible

" line numbers
set relativenumber

" search
set incsearch
set hlsearch
set ignorecase

" invisible characters
set list
set listchars=tab:→\ ,lead:·,trail:·,nbsp:+,eol:¬

" indent
set expandtab
set tabstop=2
