#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
    height=24
    padding_left=20
    padding_right=20
    color=0xff2d353b
)

default=(
    icon.font="Hack Nerd Font:Bold:16.0"
    icon.color=0xff829191
    label.font="Hack Nerd Font:Bold:16.0"
    label.color=0xff829191
    padding_left=5
    padding_right=5
    label.padding_left=4
    label.padding_right=4
    icon.padding_left=4
    icon.padding_right=4
)

clock=(
    update_freq=10
    icon=
    script="$PLUGIN_DIR/clock.sh"
)

volume=(
    script="$PLUGIN_DIR/volume.sh"
)

battery=(
    update_freq=120
    script="$PLUGIN_DIR/battery.sh"
)

focus=(
    update_freq=1
    script="$PLUGIN_DIR/focus.sh"
)

sketchybar --bar "${bar[@]}" \
    --default "${default[@]}" \
    --add item clock right \
    --set clock "${clock[@]}" \
    --add item volume right \
    --set volume "${volume[@]}" \
    --subscribe volume volume_change \
    --add item battery right \
    --set battery "${battery[@]}"\
    --subscribe battery system_woke power_source_change \
    --add item focus right \
    --set focus "${focus[@]}"

SPACE_ICONS=("I" "II" "III" "IV" "V" "VI")

for i in "${!SPACE_ICONS[@]}"
do
    sid=$(($i+1))
    sketchybar --add space space.$sid left \
        --set space.$sid space=$sid \
        icon=${SPACE_ICONS[i]} \
        background.color=0xff4f585e \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label.drawing=off \
        script="$PLUGIN_DIR/space.sh"
done

sketchybar --update
