#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

bar=(
    height=30
    padding_left=10
    padding_right=0
    color=0xff2d353b
)

default=(
    icon.font="Hack Nerd Font:Bold:16.0"
    icon.color=0xff829191
    label.font="Hack Nerd Font:Bold:16.0"
    label.color=0xff829191
    update_freq=1
    label.padding_right=10
    icon.padding_right=6
)

clock=(
    script="$PLUGIN_DIR/clock.sh"
)

battery=(
    update_freq=120
    script="$PLUGIN_DIR/battery.sh"
)

volume=(
    script="$PLUGIN_DIR/volume.sh"
)

focus=(
    script="$PLUGIN_DIR/focus.sh"
)

input=(
    script="$PLUGIN_DIR/input.sh"
)

sketchybar --bar "${bar[@]}" \
    --default "${default[@]}" \
    --add item clock right \
    --set clock "${clock[@]}" \
    --add item input right \
    --set input "${input[@]}" \
    --add item battery right \
    --set battery "${battery[@]}"\
    --subscribe battery system_woke power_source_change \
    --add item volume right \
    --set volume "${volume[@]}" \
    --subscribe volume volume_change \
    --add item focus right \
    --set focus "${focus[@]}"

SPACE_ICONS=("I" "II" "III" "IV" "V" )

for i in "${!SPACE_ICONS[@]}"
do
    sid=$(($i+1))
    sketchybar --add space space.$sid left \
        --set space.$sid space=$sid \
        icon=${SPACE_ICONS[i]} \
        background.color=0xff4f585e \
        background.corner_radius=6 \
        background.height=22 \
        background.drawing=off \
        label.drawing=off \
        icon.padding_left=5 \
        script="$PLUGIN_DIR/space.sh"
done

sketchybar --update
