#!/usr/bin/env bash

spacebar -m config position             top
spacebar -m config height               30
spacebar -m config title                off
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config dnd                  on
spacebar -m config padding_left         30
spacebar -m config padding_right        30
spacebar -m config spacing_left         20
spacebar -m config spacing_right        30
spacebar -m config text_font            "Hack Nerd Font:Bold:16.0"
spacebar -m config icon_font            "Hack Nerd Font:Bold:16.0"
# Everforest Light Medium theme colors
spacebar -m config background_color     0xff232a2e
spacebar -m config foreground_color     0xff829191
spacebar -m config space_icon_color     0xff3a94c5
spacebar -m config power_icon_color     0xff93b259
spacebar -m config battery_icon_color   0xffe66868
spacebar -m config dnd_icon_color       0xff829191
spacebar -m config clock_icon_color     0xff829191
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y %R"
