# Oh My Zsh
ZSH_THEME="gnzh"

plugins=( \
        zsh-autosuggestions \
        git \
        autojump \
    )

source $HOME/.oh-my-zsh/oh-my-zsh.sh

export EDITOR='vim'

# GNU grep
PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

source ~/.env-secrets
source ~/.panther-aliases
