# Oh My Zsh
ZSH_THEME="gnzh"

plugins=(
  zsh-autosuggestions
  autojump
  sudo
  git
  docker-compose
)

source $HOME/.oh-my-zsh/oh-my-zsh.sh

# GNU grep
PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init --no-rehash -)"

export EDITOR='vim'
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY
setopt AUTO_CD
setopt CORRECT

alias ssh="kitten ssh"

[ -f ~/.env-secrets ] && source ~/.env-secrets
[ -f ~/.panther-aliases ] && source ~/.panther-aliases
export PATH="$HOME/.local/bin:$PATH"

# Pyenv variables
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

# add Pulumi to the PATH
export PATH=$PATH:/Users/panos/.pulumi/bin
