# Oh My Zsh
ZSH_THEME="gnzh"

plugins=(
  zsh-autosuggestions
  autojump
  sudo
  git
  docker-compose
)

source $HOME/.oh-my-zsh/oh-my-zsh.sh

# GNU grep
PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init --no-rehash -)"

export EDITOR='vim'
export HISTSIZE=100_000

alias ssh="kitten ssh"

source ~/.env-secrets
source ~/.panther-aliases
export PATH="$HOME/.local/bin:$PATH"
